import JSZip from 'jszip';

function hash32(str, seed) {
  let h = 0x811c9dc5 ^ seed;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

export function stableUuid(seed) {
  const parts = [0, 1, 2, 3].map((i) => hash32(seed, i * 7919).toString(16).padStart(8, '0'));
  const hex = parts.join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-8${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

export function hasResourcePack(pack) {
  return Boolean(pack && (pack.items.length || pack.blocks.length));
}

export async function buildResourcePack(pack) {
  const zip = new JSZip();
  const versionParts = String(pack.version || '1.0.0').split('.').map((p) => parseInt(p, 10) || 0);
  while (versionParts.length < 3) versionParts.push(0);
  const version = versionParts.slice(0, 3);

  zip.file('manifest.json', JSON.stringify({
    format_version: 2,
    header: {
      name: `${pack.name} Resources`,
      description: `Textures for the ${pack.name} plugin (generated by PowerScratchedX)`,
      uuid: stableUuid(pack.name + ':header'),
      version,
      min_engine_version: [1, 20, 0],
    },
    modules: [
      {
        type: 'resources',
        uuid: stableUuid(pack.name + ':resources'),
        version,
      },
    ],
  }, null, 2));

  if (pack.items.length) {
    const textureData = {};
    for (const item of pack.items) {
      textureData[item.key] = { textures: item.path };
    }
    zip.file('textures/item_texture.json', JSON.stringify({
      resource_pack_name: pack.name,
      texture_name: 'atlas.items',
      texture_data: textureData,
    }, null, 2));
  }

  if (pack.blocks.length) {
    const textureData = {};
    for (const block of pack.blocks) {
      textureData[block.key] = { textures: block.path };
    }
    zip.file('textures/terrain_texture.json', JSON.stringify({
      resource_pack_name: pack.name,
      texture_name: 'atlas.terrain',
      padding: 8,
      num_mip_levels: 4,
      texture_data: textureData,
    }, null, 2));
  }

  for (const file of pack.files || []) {
    zip.file(file.path, file.data);
  }

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
}
