import { C } from './blocks/colors.js';

const shadowText = (text) => ({ shadow: { type: 'text', fields: { TEXT: text } } });
const shadowNum = (num) => ({ shadow: { type: 'math_number', fields: { NUM: num } } });
const shadowPlayer = () => ({ shadow: { type: 'player_current' } });

const block = (type, inputs = {}, fields = {}) => ({ kind: 'block', type, inputs, fields });
const withPlayer = (type, inputs = {}, fields = {}) => block(type, { PLAYER: shadowPlayer(), ...inputs }, fields);

export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category', name: 'Events', colour: C.events,
      contents: [
        block('evt_enable'), block('evt_disable'),
        block('evt_player_join'), block('evt_player_quit'), block('evt_player_chat'), block('evt_player_command'),
        block('evt_block_break'), block('evt_block_place'), block('evt_player_interact'),
        block('evt_player_death'), block('evt_player_respawn'), block('evt_player_damage'), block('evt_player_move'),
        { kind: 'sep' },
        block('evt_cancel'),
        block('evt_message'),
        block('evt_set_message', { TEXT: shadowText('hello') }),
        block('evt_set_broadcast', { TEXT: shadowText('') }),
        block('evt_block_id'), block('evt_block_coord'), block('evt_item_id'),
        block('evt_damage'), block('evt_set_damage', { VALUE: shadowNum(1) }),
      ],
    },
    {
      kind: 'category', name: 'Player', colour: C.player,
      contents: [
        block('player_current'),
        block('player_by_name', { NAME: shadowText('Steve') }),
        withPlayer('player_send_message', { TEXT: shadowText('Hello!') }),
        withPlayer('player_send_title', { TITLE: shadowText('Title'), SUB: shadowText('') }),
        withPlayer('player_send_bar', { TEXT: shadowText('Hello!') }),
        withPlayer('player_teleport', { X: shadowNum(0), Y: shadowNum(100), Z: shadowNum(0) }),
        withPlayer('player_teleport_to', { TARGET: { shadow: { type: 'player_by_name', inputs: { NAME: shadowText('Steve') } } } }),
        withPlayer('player_teleport_spawn'),
        withPlayer('player_give_item', { ITEM: shadowText('minecraft:diamond'), COUNT: shadowNum(1) }),
        withPlayer('player_clear_inventory'),
        withPlayer('player_kick', { REASON: shadowText('Kicked') }),
        withPlayer('player_set_gamemode'),
        withPlayer('player_set_health', { VALUE: shadowNum(20) }),
        withPlayer('player_set_food', { VALUE: shadowNum(20) }),
        withPlayer('player_add_effect', { SECONDS: shadowNum(30), LEVEL: shadowNum(1) }),
        withPlayer('player_clear_effects'),
        withPlayer('player_set_fire', { SECONDS: shadowNum(5) }),
        withPlayer('player_add_xp', { VALUE: shadowNum(10) }),
        withPlayer('player_run_command', { CMD: shadowText('say hi') }),
        withPlayer('player_set_op'),
        withPlayer('player_play_sound', { SOUND: shadowText('random.levelup') }),
        withPlayer('player_set_display_name', { NAME: shadowText('Name') }),
        { kind: 'sep' },
        withPlayer('player_name'), withPlayer('player_health'), withPlayer('player_food'),
        withPlayer('player_coord'), withPlayer('player_world'), withPlayer('player_gamemode'),
        withPlayer('player_item_in_hand'),
        withPlayer('player_has_permission', { PERM: shadowText('myplugin.use') }),
        withPlayer('player_is_op'), withPlayer('player_is_online'), withPlayer('player_is_sneaking'),
      ],
    },
    {
      kind: 'category', name: 'Server', colour: C.server,
      contents: [
        block('server_broadcast', { TEXT: shadowText('Hello everyone!') }),
        block('server_run_command', { CMD: shadowText('say hi') }),
        block('server_log', { TEXT: shadowText('Plugin loaded') }),
        block('server_foreach_player'),
        block('server_online_count'), block('server_online_names'),
        block('server_set_block', { X: shadowNum(0), Y: shadowNum(64), Z: shadowNum(0), BLOCK: shadowText('minecraft:stone') }),
        block('server_get_block', { X: shadowNum(0), Y: shadowNum(64), Z: shadowNum(0) }),
        block('server_set_time', { TIME: shadowNum(6000) }),
        block('server_play_sound_at', { X: shadowNum(0), Y: shadowNum(64), Z: shadowNum(0), SOUND: shadowText('random.explode') }),
        block('server_world_name'),
      ],
    },
    {
      kind: 'category', name: 'Commands', colour: C.commands,
      contents: [
        block('cmd_hat'),
        block('cmd_reply', { TEXT: shadowText('Done!') }),
        block('cmd_sender_name'), block('cmd_sender_is_player'),
        block('cmd_arg', { INDEX: shadowNum(1) }), block('cmd_arg_count'), block('cmd_args_joined'),
        { kind: 'sep' },
        block('perm_define'),
      ],
    },
    {
      kind: 'category', name: 'Custom Items', colour: C.items,
      contents: [
        block('item_define'),
        block('iprop_damage'), block('iprop_durability'), block('iprop_stack'), block('iprop_glint'),
        block('iprop_cooldown'), block('iprop_usable'), block('iprop_armor'), block('iprop_food'), block('iprop_hand_equipped'),
        { kind: 'sep' },
        block('evt_item_use'), block('evt_item_hit'), block('evt_item_consume'), block('evt_item_held'),
        block('item_full_id'),
        withPlayer('item_cooldown_set', { ITEM: shadowText('ruby_sword'), SECONDS: shadowNum(2) }),
        withPlayer('item_cooldown_active', { ITEM: shadowText('ruby_sword') }),
        withPlayer('player_holding', { ITEM: shadowText('ruby_sword') }),
        withPlayer('player_wearing', { ITEM: shadowText('ruby_helmet') }),
        withPlayer('player_remove_effect'),
        { kind: 'sep' },
        block('target_player'), block('target_is_player'), block('target_name'), block('target_health'),
        block('target_set_fire', { SECONDS: shadowNum(5) }),
        block('target_add_effect', { SECONDS: shadowNum(10), LEVEL: shadowNum(1) }),
        block('target_set_health', { VALUE: shadowNum(1) }),
      ],
    },
    {
      kind: 'category', name: 'Custom Blocks', colour: C.blocks,
      contents: [
        block('block_define'),
        block('bprop_hardness'), block('bprop_resistance'), block('bprop_light'), block('bprop_friction'), block('bprop_transparent'),
        { kind: 'sep' },
        block('evt_block_use'), block('block_full_id'),
      ],
    },
    {
      kind: 'category', name: 'Packets', colour: C.packets,
      contents: [
        block('evt_packet_receive'), block('evt_packet_send'),
        block('packet_type'),
        block('packet_get', { FIELD: shadowText('message') }),
        block('packet_set', { FIELD: shadowText('message'), VALUE: shadowText('') }),
        { kind: 'sep' },
        {
          kind: 'block', type: 'packet_send', inputs: {
            PLAYER: shadowPlayer(),
            FIELDS: { block: { type: 'pfield', fields: { FIELD: 'title' }, inputs: { VALUE: shadowText('Hello') }, next: { block: { type: 'pfield', fields: { FIELD: 'content' }, inputs: { VALUE: shadowText('World') } } } } },
          },
        },
        block('pfield', { VALUE: shadowText('') }),
        withPlayer('packet_transfer', { ADDRESS: shadowText('play.example.com'), PORT: shadowNum(19132) }),
        withPlayer('packet_toast', { TITLE: shadowText('Title'), CONTENT: shadowText('Message') }),
      ],
    },
    {
      kind: 'category', name: 'Forms', colour: C.forms,
      contents: [
        {
          kind: 'block', type: 'form_simple', inputs: {
            PLAYER: shadowPlayer(), TITLE: shadowText('Menu'), CONTENT: shadowText('Choose an option'),
            ELEMENTS: { block: { type: 'fbutton', inputs: { TEXT: shadowText('Option 1'), IMAGE: shadowText('') }, next: { block: { type: 'fbutton', inputs: { TEXT: shadowText('Option 2'), IMAGE: shadowText('') } } } } },
          },
        },
        block('fbutton', { TEXT: shadowText('Button'), IMAGE: shadowText('') }),
        {
          kind: 'block', type: 'form_modal', inputs: {
            PLAYER: shadowPlayer(), TITLE: shadowText('Confirm'), CONTENT: shadowText('Are you sure?'), YES: shadowText('Yes'), NO: shadowText('No'),
          },
        },
        {
          kind: 'block', type: 'form_custom', inputs: {
            PLAYER: shadowPlayer(), TITLE: shadowText('Settings'),
            ELEMENTS: { block: { type: 'fel_input', inputs: { TEXT: shadowText('Your name'), PLACEHOLDER: shadowText('Steve'), DEFAULT: shadowText('') }, next: { block: { type: 'fel_toggle', inputs: { TEXT: shadowText('Enable') } } } } },
          },
        },
        block('fel_label', { TEXT: shadowText('Some text') }),
        block('fel_header', { TEXT: shadowText('Section') }),
        block('fel_divider'),
        block('fel_input', { TEXT: shadowText('Name'), PLACEHOLDER: shadowText(''), DEFAULT: shadowText('') }),
        block('fel_toggle', { TEXT: shadowText('Enable') }),
        block('fel_slider', { TEXT: shadowText('Amount'), MIN: shadowNum(0), MAX: shadowNum(100), STEP: shadowNum(1), DEFAULT: shadowNum(50) }),
        block('fel_dropdown', { TEXT: shadowText('Color'), OPTIONS: shadowText('Red, Green, Blue'), DEFAULT: shadowNum(1) }),
        block('fel_stepslider', { TEXT: shadowText('Size'), OPTIONS: shadowText('Small, Medium, Large'), DEFAULT: shadowNum(2) }),
        { kind: 'sep' },
        block('form_button_text'), block('form_button_index'),
        block('form_value', { INDEX: shadowNum(1) }), block('form_value_index', { INDEX: shadowNum(1) }),
      ],
    },
    {
      kind: 'category', name: 'Config', colour: C.config,
      contents: [
        block('cfg_default', { VALUE: shadowText('value') }),
        block('cfg_get', { KEY: shadowText('message') }),
        block('cfg_set', { KEY: shadowText('message'), VALUE: shadowText('value') }),
        block('cfg_has', { KEY: shadowText('message') }),
        block('cfg_reload'),
      ],
    },
    {
      kind: 'category', name: 'Control', colour: C.control,
      contents: [
        block('controls_if'),
        { kind: 'block', type: 'controls_if', extraState: { hasElse: true } },
        block('controls_repeat_ext', { TIMES: shadowNum(10) }),
        block('controls_whileUntil'),
        block('ctrl_stop'),
      ],
    },
    {
      kind: 'category', name: 'Time', colour: C.time,
      contents: [
        block('time_every'),
        block('time_wait', { TICKS: shadowNum(20) }),
        block('time_now'),
      ],
    },
    {
      kind: 'category', name: 'Operators', colour: C.operators,
      contents: [
        block('math_number', {}, { NUM: 0 }),
        block('math_arithmetic', { A: shadowNum(1), B: shadowNum(1) }),
        block('math_modulo', { DIVIDEND: shadowNum(10), DIVISOR: shadowNum(3) }),
        block('math_random_int', { FROM: shadowNum(1), TO: shadowNum(10) }),
        block('math_round', { NUM: shadowNum(3.14) }),
        block('op_to_number', { VALUE: shadowText('42') }),
        { kind: 'sep' },
        block('logic_compare', { A: shadowNum(1), B: shadowNum(1) }),
        block('logic_compare', { A: shadowText('abc'), B: shadowText('abc') }),
        block('logic_operation'),
        block('logic_negate'),
        block('logic_boolean'),
        { kind: 'sep' },
        block('text', {}, { TEXT: '' }),
        block('text_join', { ADD0: shadowText('Hello '), ADD1: shadowText('world') }),
        block('text_length', { VALUE: shadowText('abc') }),
        block('op_contains', { TEXT: shadowText('hello world'), PART: shadowText('world') }),
        block('op_starts_with', { TEXT: shadowText('hello'), PART: shadowText('he') }),
        block('op_replace', { TEXT: shadowText('hello'), FROM: shadowText('l'), TO: shadowText('L') }),
        block('op_color'),
      ],
    },
    {
      kind: 'category', name: 'Variables', colour: C.variables, custom: 'VARIABLE',
    },
    {
      kind: 'category', name: 'Lists', colour: C.lists,
      contents: [
        block('list_add', { NAME: shadowText('frozen'), VALUE: shadowText('Steve') }),
        block('list_remove', { NAME: shadowText('frozen'), VALUE: shadowText('Steve') }),
        block('list_remove_at', { NAME: shadowText('frozen'), INDEX: shadowNum(1) }),
        block('list_set', { NAME: shadowText('frozen'), INDEX: shadowNum(1), VALUE: shadowText('Steve') }),
        block('list_clear', { NAME: shadowText('frozen') }),
        { kind: 'sep' },
        block('list_contains', { NAME: shadowText('frozen'), VALUE: shadowText('Steve') }),
        block('list_length', { NAME: shadowText('frozen') }),
        block('list_item', { NAME: shadowText('frozen'), INDEX: shadowNum(1) }),
        block('list_index_of', { NAME: shadowText('frozen'), VALUE: shadowText('Steve') }),
        block('list_join', { NAME: shadowText('frozen'), SEP: shadowText(', ') }),
        { kind: 'sep' },
        block('list_foreach', { NAME: shadowText('frozen') }),
        block('list_current'),
      ],
    },
    {
      kind: 'category', name: 'Player data', colour: C.pdata,
      contents: [
        withPlayer('pdata_set', { KEY: shadowText('frozen'), VALUE: shadowText('true') }),
        withPlayer('pdata_change', { KEY: shadowText('coins'), DELTA: shadowNum(1) }),
        withPlayer('pdata_remove', { KEY: shadowText('frozen') }),
        withPlayer('pdata_clear'),
        { kind: 'sep' },
        withPlayer('pdata_get', { KEY: shadowText('coins') }),
        withPlayer('pdata_has', { KEY: shadowText('frozen') }),
        { kind: 'sep' },
        block('pdata_set_name', { NAME: shadowText('Steve'), KEY: shadowText('frozen'), VALUE: shadowText('true') }),
        block('pdata_get_name', { NAME: shadowText('Steve'), KEY: shadowText('coins') }),
      ],
    },
  ],
};
